name: makefile

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  makefile:
    name: Run Makefile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --prune --unshallow

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Execute make
      shell: bash
      run: make
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Deli
        path: Deli.zip
