name: master

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  src:
    name: Build source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Unshallow repository
        run: git fetch --prune --unshallow

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Execute make
        shell: bash
        run: make -C src

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Deli
          path: src/Deli.zip
  docs:
    name: Build and publish docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json

      - name: Publish documentation to GitHub Pages
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: docs/_site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages