name: src

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  src:
    name: Build source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      
      - name: Unshallow repository
        run: git fetch --prune --unshallow

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Execute make
        run: make -C src

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Deli
          path: src/Deli.zip