name: tag

on:
  push:
    tags:
      - v*

jobs:
  src:
    name: Build and publish source
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Execute make
        shell: bash
        run: make -C src VERSION="${GITHUB_REF/refs\/tags\/v/}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Deli
          path: |
            src/nuget/*
            src/Deli.zip

      - name: Push to nuget.org
        shell: bash
        run: dotnet nuget push "src/nuget/*.nupkg" -k "$KEY" -s https://api.nuget.org/v3/index.json
        env:
          KEY: ${{ secrets.NUGET_API_KEY }}